name: Generate whitelist

on:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/generate-whitelist.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Download official whitelist
        run: curl -sSfL https://cdn2.arkdedicated.com/asa/OfficialPVECosmeticWhitelist.txt -o OfficialPVECosmeticWhitelist.txt

      - name: Generate whitelist
        run: cargo run -- data/overrides.yaml docs/whitelist.txt OfficialPVECosmeticWhitelist.txt

      - name: Commit changes
        run: |
          if git status --porcelain docs/whitelist.txt | grep .; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/whitelist.txt
            git commit -m "chore: update whitelist"
            git push
          else
            echo "No changes in docs/whitelist.txt"
          fi

